## 1. Загрузите данные, проверьте правильность, наличие пропущенных значений, типы данных.

In [1]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [2]:
cars = pd.read_csv('C:/Users/majkl/WorkSpace/Project_st_6/cars.csv')
cars.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [3]:
cars.isnull().sum()

car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

## 2. Создайте новый признак – марку автомобиля (company). Машины каких производителей встречаются в датасете? Далее исправьте названия и проверьте изменения.

In [4]:
cars['CarName'] = cars.CarName.apply(lambda x: x.split(' ')[0])
cars.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [5]:
cars.CarName.nunique()

28

In [6]:
cars.CarName.unique()

array(['alfa-romero', 'audi', 'bmw', 'chevrolet', 'dodge', 'honda',
       'isuzu', 'jaguar', 'maxda', 'mazda', 'buick', 'mercury',
       'mitsubishi', 'Nissan', 'nissan', 'peugeot', 'plymouth', 'porsche',
       'porcshce', 'renault', 'saab', 'subaru', 'toyota', 'toyouta',
       'vokswagen', 'volkswagen', 'vw', 'volvo'], dtype=object)

In [15]:
def clean_brand_names(line):
    brand = line["CarName"]
    if brand == "maxda":
        return "mazda"
    elif brand == "vokswagen" or brand == "vw":
        return "volkswagen"
    elif brand == "Nissan":
        return "nissan"
    elif brand == "porcshce":
        return "porsche"
    elif brand == "toyouta":
        return "toyota"
    else:
        return brand

In [18]:
cars["CarName"] = cars.apply(lambda line: clean_brand_names(line), axis=1)
cars.CarName.nunique()

22

In [19]:
cars.CarName.unique()

array(['alfa-romero', 'audi', 'bmw', 'chevrolet', 'dodge', 'honda',
       'isuzu', 'jaguar', 'mazda', 'buick', 'mercury', 'mitsubishi',
       'nissan', 'peugeot', 'plymouth', 'porsche', 'renault', 'saab',
       'subaru', 'toyota', 'volkswagen', 'volvo'], dtype=object)

## 3. Посчитайте корреляцию между price и другими переменными.

In [20]:
cars_2 = cars[['CarName', 'fueltype', 'aspiration', 'carbody', 'drivewheel', 'wheelbase', 'carlength', 'carwidth',
            'curbweight', 'enginetype', 'cylindernumber', 'enginesize', 'boreratio', 'horsepower', 'price']]
cars_2.head()

,CarName,fueltype,aspiration,carbody,drivewheel,wheelbase,carlength,carwidth,curbweight,enginetype,cylindernumber,enginesize,boreratio,horsepower,price
0,alfa-romero,gas,std,convertible,rwd,88.6,168.8,64.1,2548,dohc,four,130,3.47,111,13495.0
1,alfa-romero,gas,std,convertible,rwd,88.6,168.8,64.1,2548,dohc,four,130,3.47,111,16500.0
2,alfa-romero,gas,std,hatchback,rwd,94.5,171.2,65.5,2823,ohcv,six,152,2.68,154,16500.0
3,audi,gas,std,sedan,fwd,99.8,176.6,66.2,2337,ohc,four,109,3.19,102,13950.0
4,audi,gas,std,sedan,4wd,99.4,176.6,66.4,2824,ohc,five,136,3.19,115,17450.0

In [28]:
cars_2.corr(numeric_only=True)

,wheelbase,carlength,carwidth,curbweight,enginesize,boreratio,horsepower,price
wheelbase,1.000000,0.874587,0.795144,0.776386,0.569329,0.488750,0.353294,0.577816
carlength,0.874587,1.000000,0.841118,0.877728,0.683360,0.606454,0.552623,0.682920
carwidth,0.795144,0.841118,1.000000,0.867032,0.735433,0.559150,0.640732,0.759325
curbweight,0.776386,0.877728,0.867032,1.000000,0.850594,0.648480,0.750739,0.835305
enginesize,0.569329,0.683360,0.735433,0.850594,1.000000,0.583774,0.809769,0.874145
boreratio,0.488750,0.606454,0.559150,0.648480,0.583774,1.000000,0.573677,0.553173
horsepower,0.353294,0.552623,0.640732,0.750739,0.809769,0.573677,1.000000,0.808139
price,0.577816,0.682920,0.759325,0.835305,0.874145,0.553173,0.808139,1.000000

In [29]:
cars_2.corr(numeric_only=True)['price'].sort_values(ascending=False).round(2)

price         1.00
enginesize    0.87
curbweight    0.84
horsepower    0.81
carwidth      0.76
carlength     0.68
wheelbase     0.58
boreratio     0.55
Name: price, dtype: float64

## 4. Преобразуйте категориальные переменные с помощью pd.get_dummies().

In [30]:
cars_2.dtypes

CarName            object
fueltype           object
aspiration         object
carbody            object
drivewheel         object
wheelbase         float64
carlength         float64
carwidth          float64
curbweight          int64
enginetype         object
cylindernumber     object
enginesize          int64
boreratio         float64
horsepower          int64
price             float64
dtype: object

In [31]:
df_dummy = pd.get_dummies(data=cars_2[['CarName', 'fueltype', 'aspiration', 'carbody', 'drivewheel', 'enginetype', \
                                       'cylindernumber']], drop_first = True)
df_dummy.head()

,CarName_audi,CarName_bmw,CarName_buick,CarName_chevrolet,CarName_dodge,CarName_honda,CarName_isuzu,CarName_jaguar,CarName_mazda,CarName_mercury,...,enginetype_ohc,enginetype_ohcf,enginetype_ohcv,enginetype_rotor,cylindernumber_five,cylindernumber_four,cylindernumber_six,cylindernumber_three,cylindernumber_twelve,cylindernumber_two
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,True,False,False,False
3,True,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,True,False,False,False,False
4,True,False,False,False,False,False,False,False,False,False,...,True,False,False,False,True,False,False,False,False,False

In [33]:
cars_new = pd.concat([cars_2, df_dummy], axis=1)
cars_new = cars_new.drop(columns=['CarName', 'fueltype', 'aspiration', 'carbody', 'drivewheel', 'enginetype', 'cylindernumber'])
cars_new.head()

,wheelbase,carlength,carwidth,curbweight,enginesize,boreratio,horsepower,price,CarName_audi,CarName_bmw,...,enginetype_ohc,enginetype_ohcf,enginetype_ohcv,enginetype_rotor,cylindernumber_five,cylindernumber_four,cylindernumber_six,cylindernumber_three,cylindernumber_twelve,cylindernumber_two
0,88.6,168.8,64.1,2548,130,3.47,111,13495.0,False,False,...,False,False,False,False,False,True,False,False,False,False
1,88.6,168.8,64.1,2548,130,3.47,111,16500.0,False,False,...,False,False,False,False,False,True,False,False,False,False
2,94.5,171.2,65.5,2823,152,2.68,154,16500.0,False,False,...,False,False,True,False,False,False,True,False,False,False
3,99.8,176.6,66.2,2337,109,3.19,102,13950.0,True,False,...,True,False,False,False,False,True,False,False,False,False
4,99.4,176.6,66.4,2824,136,3.19,115,17450.0,True,False,...,True,False,False,False,True,False,False,False,False,False

In [34]:
cars_new.shape

(205, 49)

## 5. Постройте модель с одним предиктором цены – horsepower. Какой процент изменчивости объясняет полученная модель? (\(R^2\))

In [36]:
results = smf.ols('price ~ horsepower', cars_new).fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.653
Model:                            OLS   Adj. R-squared:                  0.651
Method:                 Least Squares   F-statistic:                     382.2
Date:                 Пн, 07 апр 2025   Prob (F-statistic):           1.48e-48
Time:                        11:43:52   Log-Likelihood:                -2024.0
No. Observations:                 205   AIC:                             4052.
Df Residuals:                     203   BIC:                             4059.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -3721.7615    929.849     -4.003      0.000   -5555.163   -1888.360
horsepower   163.2631      8.351     19.549      0.000     146.796     179.730
==============================================================================
Omnibus:                       47.741   Durbin-Watson:                   0.792
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               91.702
Skew:                           1.141   Prob(JB):                     1.22e-20
Kurtosis:                       5.352   Cond. No.                         314.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

## 6. Далее – две модели (со всеми предикторами и со всеми, кроме марок машин). Обратите внимание на изменения в \(R^2\), коэффициентах и их значимости. Какую модель лучше оставить?

Лучше оставить модель, где  меньше предикторов, ведь R2 изменился не очень сильно, а часть марок вообще не значима

In [41]:
cars_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 49 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   wheelbase              205 non-null    float64
 1   carlength              205 non-null    float64
 2   carwidth               205 non-null    float64
 3   curbweight             205 non-null    int64
 4   enginesize             205 non-null    int64
 5   boreratio              205 non-null    float64
 6   horsepower             205 non-null    int64
 7   price                  205 non-null    float64
 8   CarName_audi           205 non-null    bool
 9   CarName_bmw            205 non-null    bool
 10  CarName_buick          205 non-null    bool
 11  CarName_chevrolet      205 non-null    bool
 12  CarName_dodge          205 non-null    bool
 13  CarName_honda          205 non-null    bool
 14  CarName_isuzu          205 non-null    bool
 15  CarName_jaguar         205 non-null    bool
 16  CarName_mazda          205 non-null    bool
 17  CarName_mercury        205 non-null    bool
 18  CarName_mitsubishi     205 non-null    bool
 19  CarName_nissan         205 non-null    bool
 20  CarName_peugeot        205 non-null    bool
 21  CarName_plymouth       205 non-null    bool
 22  CarName_porsche        205 non-null    bool
 23  CarName_renault        205 non-null    bool
 24  CarName_saab           205 non-null    bool
 25  CarName_subaru         205 non-null    bool
 26  CarName_toyota         205 non-null    bool
 27  CarName_volkswagen     205 non-null    bool
 28  CarName_volvo          205 non-null    bool
 29  fueltype_gas           205 non-null    bool
 30  aspiration_turbo       205 non-null    bool
 31  carbody_hardtop        205 non-null    bool
 32  carbody_hatchback      205 non-null    bool
 33  carbody_sedan          205 non-null    bool
 34  carbody_wagon          205 non-null    bool
 35  drivewheel_fwd         205 non-null    bool
 36  drivewheel_rwd         205 non-null    bool
 37  enginetype_dohcv       205 non-null    bool
 38  enginetype_l           205 non-null    bool
 39  enginetype_ohc         205 non-null    bool
 40  enginetype_ohcf        205 non-null    bool
 41  enginetype_ohcv        205 non-null    bool
 42  enginetype_rotor       205 non-null    bool
 43  cylindernumber_five    205 non-null    bool
 44  cylindernumber_four    205 non-null    bool
 45  cylindernumber_six     205 non-null    bool
 46  cylindernumber_three   205 non-null    bool
 47  cylindernumber_twelve  205 non-null    bool
 48  cylindernumber_two     205 non-null    bool
dtypes: bool(41), float64(5), int64(3)
memory usage: 21.1 KB

In [44]:
x = cars_new.drop(['price'], axis='columns')
x = x[['wheelbase', 'carlength', 'carwidth', 'curbweight', 'enginesize', 'boreratio', 'horsepower']]
x = sm.add_constant(x)
y = cars_new['price']

In [45]:
model_1 = sm.OLS(y, x).fit()
print(model_1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.822
Model:                            OLS   Adj. R-squared:                  0.816
Method:                 Least Squares   F-statistic:                     129.8
Date:                 Пн, 07 апр 2025   Prob (F-statistic):           2.99e-70
Time:                        11:56:35   Log-Likelihood:                -1955.7
No. Observations:                 205   AIC:                             3927.
Df Residuals:                     197   BIC:                             3954.
Df Model:                           7
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -4.243e+04   1.32e+04     -3.216      0.002   -6.84e+04   -1.64e+04
wheelbase     94.7692     98.355      0.964      0.336     -99.194     288.733
carlength    -49.9229     54.438     -0.917      0.360    -157.278      57.432
carwidth     541.8531    253.601      2.137      0.034      41.731    1041.975
curbweight     2.6274      1.563      1.681      0.094      -0.455       5.710
enginesize    83.1012     12.716      6.535      0.000      58.025     108.177
boreratio  -1115.7083   1204.007     -0.927      0.355   -3490.105    1258.689
horsepower    55.4856     12.668      4.380      0.000      30.503      80.468
==============================================================================
Omnibus:                       33.173   Durbin-Watson:                   0.792
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               78.179
Skew:                           0.723   Prob(JB):                     1.06e-17
Kurtosis:                       5.657   Cond. No.                     1.44e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.44e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [46]:
cols_to_keep = cars_new.columns[~cars_new.columns.str.startswith('company_')]
cols_to_keep

Index(['wheelbase', 'carlength', 'carwidth', 'curbweight', 'enginesize',
       'boreratio', 'horsepower', 'price', 'CarName_audi', 'CarName_bmw',
       'CarName_buick', 'CarName_chevrolet', 'CarName_dodge', 'CarName_honda',
       'CarName_isuzu', 'CarName_jaguar', 'CarName_mazda', 'CarName_mercury',
       'CarName_mitsubishi', 'CarName_nissan', 'CarName_peugeot',
       'CarName_plymouth', 'CarName_porsche', 'CarName_renault',
       'CarName_saab', 'CarName_subaru', 'CarName_toyota',
       'CarName_volkswagen', 'CarName_volvo', 'fueltype_gas',
       'aspiration_turbo', 'carbody_hardtop', 'carbody_hatchback',
       'carbody_sedan', 'carbody_wagon', 'drivewheel_fwd', 'drivewheel_rwd',
       'enginetype_dohcv', 'enginetype_l', 'enginetype_ohc', 'enginetype_ohcf',
       'enginetype_ohcv', 'enginetype_rotor', 'cylindernumber_five',
       'cylindernumber_four', 'cylindernumber_six', 'cylindernumber_three',
       'cylindernumber_twelve', 'cylindernumber_two'],
      dtype='object')

In [49]:
x = cars_new[cols_to_keep].drop('price', axis='columns')
x = x[['wheelbase', 'carlength', 'carwidth', 'curbweight', 'enginesize', 'boreratio', 'horsepower']]
x = sm.add_constant(x)
y = cars_new['price']

In [50]:
model_2 = sm.OLS(y, x).fit()
print(model_2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.822
Model:                            OLS   Adj. R-squared:                  0.816
Method:                 Least Squares   F-statistic:                     129.8
Date:                 Пн, 07 апр 2025   Prob (F-statistic):           2.99e-70
Time:                        11:57:52   Log-Likelihood:                -1955.7
No. Observations:                 205   AIC:                             3927.
Df Residuals:                     197   BIC:                             3954.
Df Model:                           7
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -4.243e+04   1.32e+04     -3.216      0.002   -6.84e+04   -1.64e+04
wheelbase     94.7692     98.355      0.964      0.336     -99.194     288.733
carlength    -49.9229     54.438     -0.917      0.360    -157.278      57.432
carwidth     541.8531    253.601      2.137      0.034      41.731    1041.975
curbweight     2.6274      1.563      1.681      0.094      -0.455       5.710
enginesize    83.1012     12.716      6.535      0.000      58.025     108.177
boreratio  -1115.7083   1204.007     -0.927      0.355   -3490.105    1258.689
horsepower    55.4856     12.668      4.380      0.000      30.503      80.468
==============================================================================
Omnibus:                       33.173   Durbin-Watson:                   0.792
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               78.179
Skew:                           0.723   Prob(JB):                     1.06e-17
Kurtosis:                       5.657   Cond. No.                     1.44e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.44e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

Выбранная модель объясняет примерно 90% дисперсии (окр. до целого). Среди предикторов 10 из 27 оказались не значимыми (p > 0.05). Пример интерпретации: при единичном изменении показателя horsepower, цена ВОЗРАСТАЕТ на 86.8164 (без округления).